GET http://localhost:5000/users

###
GET http://localhost:5000/users/2

###
POST  http://localhost:5000/users
Content-Type: application/json

{
  "username": "crfr",
  "status": "Done",
  "email": "rgrfn@gmail.com",
  "note": "This is a note",
  "deadline": "2025-04-30"
}

###
PATCH http://localhost:5000/users/1
Content-Type: application/json

{
  "deadline": "2025-03-14"
  }

###
DELETE http://localhost:5000/users/1

###
GET http://localhost:5000/auth
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsInVzZXJOYW1lIjoiaGFiaWIiLCJ1c2VyRW1haWwiOiJoYWJpYmFubmFmaUBnbWFpbC5jb20iLCJpYXQiOjE3NDc3NDE2ODcsImV4cCI6MTc0Nzc0MTcxN30.Swm7M8XbY3JXSd2WHCmXfHn3rq_OFBwSTPvBkwoz4PQ

###
POST http://localhost:5000/register
Content-Type: application/json

{
  "username": "habib",
  "password": "habib123",
  "email": "habibannafi@gmail.com",
  "confrimPassword": "habib123"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
  "password": "habib123",
  "email": "habibannafi@gmail.com"
}


###
GET http://localhost:5000/token


###
DELETE http://localhost:5000/logout

